// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vmips_machine.h for the primary calling header

#include "verilated.h"

#include "Vmips_machine__Syms.h"
#include "Vmips_machine___024root.h"

VL_ATTR_COLD void Vmips_machine___024root___settle__TOP__5(Vmips_machine___024root* vlSelf);
void Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M__DOT__M02__1(Vmips_machine_Mux_24Bit* vlSelf);
void Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__D__DOT__M02__2(Vmips_machine_Mux_24Bit* vlSelf);
void Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__AS__DOT__M04__3(Vmips_machine_Mux_24Bit* vlSelf);
void Vmips_machine___024root___settle__TOP__6(Vmips_machine___024root* vlSelf);
void Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__AS__DOT__M05__4(Vmips_machine_Mux_24Bit* vlSelf);
void Vmips_machine___024root___settle__TOP__7(Vmips_machine___024root* vlSelf);
void Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M01__DOT__M01__5(Vmips_machine_Mux_24Bit* vlSelf);
void Vmips_machine___024root___settle__TOP__8(Vmips_machine___024root* vlSelf);
void Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M02__DOT__M01__6(Vmips_machine_Mux_24Bit* vlSelf);
void Vmips_machine___024root___settle__TOP__9(Vmips_machine___024root* vlSelf);
void Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M09__DOT__M01__7(Vmips_machine_Mux_24Bit* vlSelf);
void Vmips_machine___024root___settle__TOP__10(Vmips_machine___024root* vlSelf);
void Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M010__DOT__M01__8(Vmips_machine_Mux_24Bit* vlSelf);
void Vmips_machine___024root___settle__TOP__11(Vmips_machine___024root* vlSelf);
void Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M011__DOT__M01__9(Vmips_machine_Mux_24Bit* vlSelf);
void Vmips_machine___024root___settle__TOP__12(Vmips_machine___024root* vlSelf);

VL_ATTR_COLD void Vmips_machine___024root___eval_settle(Vmips_machine___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vmips_machine__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vmips_machine___024root___eval_settle\n"); );
    // Body
    Vmips_machine___024root___settle__TOP__5(vlSelf);
    Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M__DOT__M02__1((&vlSymsp->TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M__DOT__M02));
    Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__D__DOT__M02__2((&vlSymsp->TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__D__DOT__M02));
    Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__AS__DOT__M04__3((&vlSymsp->TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__AS__DOT__M04));
    Vmips_machine___024root___settle__TOP__6(vlSelf);
    Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__AS__DOT__M05__4((&vlSymsp->TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__AS__DOT__M05));
    Vmips_machine___024root___settle__TOP__7(vlSelf);
    Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M01__DOT__M01__5((&vlSymsp->TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M01__DOT__M01));
    Vmips_machine___024root___settle__TOP__8(vlSelf);
    Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M02__DOT__M01__6((&vlSymsp->TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M02__DOT__M01));
    Vmips_machine___024root___settle__TOP__9(vlSelf);
    Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M09__DOT__M01__7((&vlSymsp->TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M09__DOT__M01));
    Vmips_machine___024root___settle__TOP__10(vlSelf);
    Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M010__DOT__M01__8((&vlSymsp->TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M010__DOT__M01));
    Vmips_machine___024root___settle__TOP__11(vlSelf);
    Vmips_machine_Mux_24Bit___settle__TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M011__DOT__M01__9((&vlSymsp->TOP__mips_machine__DOT__core__DOT__f_core__DOT__alu__DOT__adder__DOT__M011__DOT__M01));
    Vmips_machine___024root___settle__TOP__12(vlSelf);
}
